name: CI

on:
  push:
    branches: [ '**' ]
    tags-ignore: [ 'v*.*.*' ]

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-test.yaml@deb-packages
    # with:
    #   deb-packages: libsodium-dev
    permissions:
      contents: read
